version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password
    ports:
      - "1433:1433"
    networks:
      - backend

  web:
    image: quanlyhethongbanhang
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db;Database=SaleManagementDB;User Id=sa;Password=YourStrong@Password;TrustServerCertificate=True
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
